[2025-08-20T15:49:08.210+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T15:49:08.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:49:05.449900+00:00 [queued]>
[2025-08-20T15:49:08.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:49:05.449900+00:00 [queued]>
[2025-08-20T15:49:08.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-20T15:49:08.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_transformation> on 2025-08-20 15:49:05.449900+00:00
[2025-08-20T15:49:08.276+0000] {standard_task_runner.py:63} INFO - Started process 29590 to run task
[2025-08-20T15:49:08.280+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_transformation_dag', 'run_data_transformation', 'manual__2025-08-20T15:49:05.449900+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmp02ssotwu']
[2025-08-20T15:49:08.281+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask run_data_transformation
[2025-08-20T15:49:08.355+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:49:05.449900+00:00 [running]> on host 4e81cb17b5ff
[2025-08-20T15:49:08.456+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_transformation_dag' AIRFLOW_CTX_TASK_ID='run_data_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T15:49:05.449900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T15:49:05.449900+00:00'
[2025-08-20T15:49:08.457+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T15:49:08.464+0000] {transformation_dag.py:16} INFO - Running data processing tasks for manual__2025-08-20T15:49:05.449900+00:00
[2025-08-20T15:49:08.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T15:49:08.468+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/airflow/dags/transformation_dag.py", line 18, in _run_data_processing
    data_processing_results = main()
  File "/opt/airflow/src/data_processors.py", line 140, in main
    process_job_postings_gold(duckdb_path)
  File "/opt/airflow/src/data_processors.py", line 30, in process_job_postings_gold
    con = duckdb.connect(duckdb_path)
duckdb.duckdb.IOException: IO Error: Cannot open file "/workspaces/nyc_hiring_audit_project/duckdb/nyc_hiring.duckdb": Permission denied
[2025-08-20T15:49:08.484+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_transformation_dag, task_id=run_data_transformation, run_id=manual__2025-08-20T15:49:05.449900+00:00, execution_date=20250820T154905, start_date=20250820T154908, end_date=20250820T154908
[2025-08-20T15:49:08.516+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task run_data_transformation (IO Error: Cannot open file "/workspaces/nyc_hiring_audit_project/duckdb/nyc_hiring.duckdb": Permission denied; 29590)
[2025-08-20T15:49:08.532+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-20T15:49:08.547+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-20T15:49:08.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
