[2025-08-20T15:26:10.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T15:26:10.340+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_acquisition_dag.run_data_acquisition scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T15:26:10.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_acquisition_dag.run_data_acquisition scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T15:26:10.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-20T15:26:10.378+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_acquisition> on 2025-08-19 00:00:00+00:00
[2025-08-20T15:26:10.384+0000] {standard_task_runner.py:63} INFO - Started process 20279 to run task
[2025-08-20T15:26:10.387+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_acquisition_dag', 'run_data_acquisition', 'scheduled__2025-08-19T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp3kl43evj']
[2025-08-20T15:26:10.389+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask run_data_acquisition
[2025-08-20T15:26:10.459+0000] {task_command.py:426} INFO - Running <TaskInstance: data_acquisition_dag.run_data_acquisition scheduled__2025-08-19T00:00:00+00:00 [running]> on host 4e81cb17b5ff
[2025-08-20T15:26:10.557+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_acquisition_dag' AIRFLOW_CTX_TASK_ID='run_data_acquisition' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T00:00:00+00:00'
[2025-08-20T15:26:10.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T15:26:10.568+0000] {ingestion_dag.py:24} INFO - Running data acquisition tasks for scheduled__2025-08-19T00:00:00+00:00
[2025-08-20T15:26:10.568+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T15:26:10.568+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/airflow/dags/ingestion_dag.py", line 26, in _run_data_acquisition
    api_results = api_call()
TypeError: api_call() missing 2 required positional arguments: 'url' and 'filename'
[2025-08-20T15:26:10.581+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_acquisition_dag, task_id=run_data_acquisition, run_id=scheduled__2025-08-19T00:00:00+00:00, execution_date=20250819T000000, start_date=20250820T152610, end_date=20250820T152610
[2025-08-20T15:26:10.611+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task run_data_acquisition (api_call() missing 2 required positional arguments: 'url' and 'filename'; 20279)
[2025-08-20T15:26:10.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-20T15:26:10.654+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-20T15:26:10.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
